version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ./temp_uploads:/app/temp_uploads
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - ALLOWED_ORIGINS=http://localhost:5173
    restart: unless-stopped

volumes:
  redis_data: