version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ./jobs:/app/jobs
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - ./temp:/app/temp
      - ./jobs:/app/jobs
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data: