name: audioforma-stems
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - fastapi
  - uvicorn
  - python-multipart
  - pydub
  - python-dotenv
  - celery
  - redis-py
  - ffmpeg
  - requests
  - pip:
    - demucs
  - aiohttp
  - aiofiles