name: audioforma-stems
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - fastapi=0.109.0
  - uvicorn=0.27.0
  - python-multipart=0.0.7
  - pydub=0.25.1
  - python-dotenv=1.0.0
  - celery=5.3.6
  - redis-py=5.0.1
  - ffmpeg=6.1.1
  - requests=2.31.0
  - aiohttp=3.9.1
  - aiofiles=23.2.1
  - pip:
    - demucs==4.0.1